services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: widi_php
    volumes:
      - .:/var/www/html
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB=widi_db
    depends_on:
      - mongodb
    networks:
      - widi_network

  nginx:
    image: nginx:alpine
    container_name: widi_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - widi_network

  mongodb:
    image: mongo:6.0
    container_name: widi_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - widi_network

volumes:
  mongodb_data:

networks:
  widi_network:
    driver: bridge
